CREATE FUNCTION EventoActivo()
RETURNS INT
AS BEGIN
  DECLARE @ID_EVENTO INT;

  SELECT TOP 1 @ID_EVENTO = idEvento
  FROM Evento
  WHERE GETDATE() BETWEEN fecha_comienzo AND fecha_acabado
  ORDER BY fecha_comienzo ASC;

  RETURN @ID_EVENTO;
END;

CREATE FUNCTION TiempoEnEvento(@MATRICULA VARCHAR(15), @ID_EVENTO INT)
RETURNS INT
AS BEGIN
  DECLARE @TIEMPO INT;

  SELECT @TIEMPO = DATEDIFF(MINUTE, FECHA_LLEGADA, ISNULL(FECHA_SALIDA, GETDATE()))
  FROM ALUMNOASISTIOEVENTO
  WHERE MATRICULA = @MATRICULA AND ID_EVENTO = @ID_EVENTO;

  RETURN @TIEMPO;
END;

CREATE TRIGGER FechaLlegada ON ALUMNOASISTIOEVENTO INSTEAD OF INSERT
AS BEGIN

  INSERT INTO ALUMNOASISTIOEVENTO (MATRICULA, ID_EVENTO, FECHA_LLEGADA, FECHA_SALIDA)
  SELECT 
    MATRICULA, ID_EVENTO, GETDATE(), FECHA_SALIDA
  FROM inserted;
END;

