USE SIMPOSIUM;
GO

CREATE FUNCTION dbo.EventoActivo() RETURNS INT AS BEGIN
  DECLARE @idEvento INT;

  SELECT TOP 1 @idEvento = idEvento
  FROM Evento
  WHERE GETDATE() BETWEEN fecha_comienzo AND fecha_acabado
  ORDER BY fecha_comienzo ASC;

  RETURN @idEvento;
END;
GO

CREATE FUNCTION dbo.TiempoEnEvento(@MATRICULA VARCHAR(15), @idEvento INT) RETURNS INT AS BEGIN
  DECLARE @TIEMPO INT;

  SELECT @TIEMPO = DATEDIFF(MINUTE, FECHA_LLEGADA, ISNULL(FECHA_SALIDA, GETDATE()))
  FROM ALUMNOASISTIOEVENTO
  WHERE MATRICULA = @MATRICULA AND idEvento = @idEvento;

  RETURN @TIEMPO;
END;
GO

CREATE TRIGGER dbo.FechaLlegada ON ALUMNOASISTIOEVENTO AFTER INSERT AS BEGIN
  UPDATE AAE
  SET FECHA_LLEGADA = ISNULL(AAE.FECHA_LLEGADA, GETDATE())
  FROM ALUMNOASISTIOEVENTO AS AAE
  INNER JOIN inserted AS src
    ON AAE.idAsistencia = src.idAsistencia;
END;
GO
