USE SIMPOSIUM;
GO

CREATE FUNCTION dbo.EventoActivo()
RETURNS INT
AS BEGIN
  DECLARE @idEvento INT;

  SELECT TOP 1 @idEvento = idEvento
  FROM Evento
  WHERE GETDATE() BETWEEN fecha_comienzo AND fecha_acabado
  ORDER BY fecha_comienzo ASC;

  RETURN @idEvento;
END;
GO

CREATE FUNCTION dbo.TiempoEnEvento(@MATRICULA VARCHAR(15), @idEvento INT)
RETURNS INT
AS BEGIN
  DECLARE @TIEMPO INT;

  SELECT @TIEMPO = DATEDIFF(MINUTE, FECHA_LLEGADA, ISNULL(FECHA_SALIDA, GETDATE()))
  FROM ALUMNOASISTIOEVENTO
  WHERE MATRICULA = @MATRICULA AND idEvento = @idEvento;

  RETURN @TIEMPO;
END;
GO

CREATE TRIGGER dbo.FechaLlegada ON ALUMNOASISTIOEVENTO INSTEAD OF INSERT
AS BEGIN

  INSERT INTO ALUMNOASISTIOEVENTO (MATRICULA, idEvento, FECHA_LLEGADA, FECHA_SALIDA)
  SELECT 
    MATRICULA, idEvento, GETDATE(), FECHA_SALIDA
  FROM inserted;
END;
GO
