USE master;
GO

CREATE LOGIN AdminEventos
WITH PASSWORD = 'Admin123!';
GO

CREATE LOGIN StaffEventos
WITH PASSWORD = 'Staff123!';
GO

USE Simposium;
GO

CREATE USER AdminEventos FOR LOGIN AdminEventos;
CREATE USER StaffEventos FOR LOGIN StaffEventos;
GO

CREATE ROLE RolAdministrador;
CREATE ROLE RolStaff;
GO

ALTER ROLE RolAdministrador ADD MEMBER AdminEventos;
ALTER ROLE RolStaff ADD MEMBER StaffEventos;
GO

GRANT EXECUTE ON dbo.EventoActivo TO RolAdministrador;
GRANT EXECUTE ON dbo.EventoActivo TO RolStaff;
GRANT EXECUTE ON dbo.sp_GetDatosAsistencia TO RolAdministrador;
GRANT EXECUTE ON dbo.sp_GetDatosAsistencia TO RolStaff;
GRANT EXECUTE ON dbo.sp_GetDatosCumplimiento TO RolAdministrador;
GRANT EXECUTE ON dbo.sp_GetDatosCumplimiento TO RolStaff;
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON Alumno TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON Evento TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON Simposium TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON AlumnoAsistioEvento TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON CARRERA TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON ESCUELA TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALUMNOINSCRITOSIMPOSIUM TO RolAdministrador;


GRANT SELECT, INSERT, UPDATE, DELETE ON Simposium TO RolStaff;
GRANT SELECT, INSERT, UPDATE, DELETE ON Alumno TO RolStaff;
GRANT SELECT ON ESCUELA TO RolStaff;
GRANT SELECT, INSERT, UPDATE, DELETE ON Evento TO RolStaff;
GRANT SELECT, INSERT, UPDATE ON AlumnoAsistioEvento TO RolStaff;
GRANT SELECT ON ALUMNOINSCRITOSIMPOSIUM TO RolStaff;

GO
